# Generated by Django 4.2.1 on 2023-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightentry',
            name='user',
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
